gems: [jekyll-paginate,jekyll-gist]

# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            W-o-M
tagline:          'A Jekyll blog'
description:      'from to...'
url:              http://www.wangm23456.cc
baseurl:          /

author:
  name:           'wangm23456'
  url:            wmg23456@gmail.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/wangm23456/wangm23456.github.io
