gems: [jekyll-paginate,jekyll-gist]

# Dependencies
markdown:       kramdown
highlighter:      rouge
kramdown:
    input:          GFM
    syntax_highlighter:       rouge
# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            W-o-M
tagline:          'A Jekyll blog'
description:      '用另一个禁锢的世界来描绘某个禁锢的世界，用虚构的故事来陈述真实的事件，两者都是合理的。'
url:              http://www.wangm23456.cc
baseurl:          /

author:
  name:           'wangm23456'
  url:            wmg23456@gmail.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/wangm23456/wangm23456.github.io
